### ISSUE TITLE
Regression in 16.10.0 release results in System.BadImageFormatException

### ISSUE THREAD

**Issue by kentcb** [dotnet/fsharp#11620]
Since the 16.10.0 VS update, the below code produces a `BadImageFormatException`. Prior to that release, it works as expected.

**Repro steps**

```fsharp
module Repro

type Data = interface end
and Service<'Data when 'Data :> Data>() = class end

type IThing = interface end
and Thing<'T> = { Metadata: 'T } with interface IThing

let createService metadata = (Service<'Data>())

let getCreateServiceCallback<'T> (thing: IThing) =
    let upcastThing =
        thing
        :?> Thing<'T>
    let getService () = createService upcastThing.Metadata
    (fun () -> getService)

[<EntryPoint>]
let main _ =
    let dummyThing : Thing<int> = { Thing.Metadata = 42 }
    // crash occurs on the following line
    let callback = getCreateServiceCallback<int> dummyThing
    let resolvedService = callback ()
    printfn "Resolved service: %A" resolvedService
    System.Console.ReadKey() |> ignore
    0
```

**Expected behavior**

Code should work as it did prior to 16.10.0, or at least produce a compiler error.

**Actual behavior**

Crashes with `BadImageFormatException` on the indicated line.

**Known workarounds**

* Marking the `getService` function as `inline`
* Explicitly annotating the `getService` return type as `Service<Data>`
* Run in release mode

**Related information**

* Windows 10
* .NET 5
* Visual Studio 2019

**Comment by cartermp** [comment]
Thanks for the repro, I can confirm it. I suspect we did regress somewhere here given that it still works in release mode. cc @TIHan

**Comment by TIHan** [comment]
Testing this, in `Release`, it does work however, I can't open the binary in ILSpy or ILDASM.
I'm not sure yet why this is occurring.

**Comment by TIHan** [comment]
`peverify` just tells us that it is bad headers.

**Comment by TIHan** [comment]
So, `getService` is type `unit -> Service<#Data>` - so being explicit with the return type via `unit -> Service<Data>` makes it a different type.

`unit -> Service<#Data>` tells us it found a free type variable due to `#Data`. This means `getService` is a `forall` type.
With it being captured in a closure, this might be the source of the issue. In release, this closure is probably getting erased.

**Comment by TIHan** [comment]
I can confirm: This regression occurred when this was merged - https://github.com/dotnet/fsharp/pull/11349 .

However, the initial fix https://github.com/dotnet/fsharp/pull/11349/commits/df4969b75913d116db779545d3b1ef78e28e47c4 works fine. It was only until subsequent changes when we tried to simplify the local type functions does this regression occur.
cc @dsyme

**Comment by dsyme** [comment]
This was fixed by #11755 .  

@TIHan @jonsequitur Don't forget we may need to apply this as a servicing fix

**Comment by dungpa** [comment]
@dsyme @TIHan Is the fix available in Visual Studio 16.11.2?

I saw a similar bug and upgrading to Visual Studio 16.11.2 didn't help.
I don't see this being mentioned in https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes either.

**Comment by dsyme** [comment]
> @dsyme @TIHan Is the fix available in Visual Studio 16.11.2?

No, it isn't. It will be in VS2022.  There is still discussion about whether it will qualify for a servicing fix.  If you have a public-facin repro for this bug (especially in Release code) please document it below.

**Comment by dungpa** [comment]
I still experience this in Release mode.
In certain cases, inlining functions could help.

This is from some private code; I'll try to find an independent repro.

**Comment by dungpa** [comment]
@dsyme Agree.
In this codebase, we have heavy use of generics; lambda lifting is not always  applicable.

It would be great if the fix goes through a service release.
We have added workarounds for a few cases, but frequently encounter this in some pull requests (compiled in Release mode in CI).

We rolled back to Visual Studio 16.9 in some machines a while ago because of the defect.
It seems that we can't upgrade to 16.11 either.
I've got a wrong impression since the fix is included in `16.11` milestone https://github.com/dotnet/fsharp/milestone/41?closed=1.

**Comment by dsyme** [comment]
> I've got a wrong impression since the fix is included in 16.11 milestone https://github.com/dotnet/fsharp/milestone/41?closed=1.

The criteria for 16.11 tightened and we didn't fully analyse this in time for a deadline, partly due to change of staff. So a combination of factors.  But my intuition is that this will need to go into a servicing release.

You can in theory workaround the problem by using .NET SDK before this was introduced, however the `fsc.exe` that ships with 16.10 and 16.11 has this problem as things currently stand.

**Comment by dungpa** [comment]
> You can in theory workaround the problem by using .NET SDK before this was introduced, however the fsc.exe that ships with 16.10 and 16.11 has this problem as things currently stand.

I tried that but couldn't make it work properly.
Moreover, we strive to keep up-to-date with Visual Studio versions; there are so many good things being added 😀.
