### ISSUE TITLE
Using a Span with an index in FSI always leads to MissingMethodException on `get_Item`

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/fsharp#9401]
When using `dotnet fsi` (I haven't managed to get `Span` working at all on the FSI in VS), I tried to run a function that compiled just fine, but when running gave a `MissingMethodException` for `get_Item`.

Running the same code from a compiled binary or during a debug session from, say, Visual Studio is not a problem.

**Repro steps**

The simplest repro is the following. It doesn't matter whether the `.[x]` part is local to a member, a function or in a module.

Start FSI with `dotnet fsi`. Then:

```f#
> #r "System.Memory.dll";;
--> Referenced 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Memory.dll' (file may be locked by F# Interactive process)
> "1234".AsSpan().[1];;
System.MissingMethodException: Method not found: '!0 ByRef System.ReadOnlySpan`1.get_Item(Int32)'.
   at <StartupCode$FSI_0013>.$FSI_0013.main@()
Stopped due to error
```

```
#r "System.Memory.dll"
open System
"1234".AsSpan().[1]
```

Other syntax also fails:

```f#
> let x = "abc".AsSpan() in x.[1];;
System.MissingMethodException: Method not found: '!0 ByRef System.ReadOnlySpan`1.get_Item(Int32)'.
   at <StartupCode$FSI_0017>.$FSI_0017.main@()
```

**Expected behavior**

It should compile and run without error and print "1" to the screen.

**Actual behavior**

See above: `MissingMethodException` on `get_Item`.

**Known workarounds**

None that I'm aware of.

**Related information**

It should be noted that `Span` and `ReadOnlySpan` are accessible, i.e., I can do this:

```f#
> let x = "abc".AsSpan() in x.ToString();;
val it : string = "abc"
```

I've discussed this issue briefly on Slack where others have confirmed this behavior.

* Windows with recent versions of Core and FSI. 
* Specific version I tried for the above was `.NET Core SDK (3.1.300-preview-015135)`.

**Comment by cartermp** [comment]
Unfortunately this is a symptom of the larger problem of span and byrefs with F# scripts. We'll need to think about this a little more holistically. Currently, byref scoping rules mean that you can't reasonably use Spans with interactive, often ad-hoc scripting. It always has to be contained within a function. Separately, we don't auto-reference the right reference set. There may also be a bug in here with regards tot he missing method exception.

**Comment by cartermp** [comment]
I'd like to tentatively say that we should have a good experience in place for Span + FSI with .NET 5.

**Comment by abelbraaksma** [comment]
> It always has to be contained within a function. 

This I knew (if you have a global var in F# assigned a span you get another error). The error mentioned in the bug report can be reproed just as well when inside a function (in fact, that's how I found out).

> we don't auto-reference the right reference set.

I know, and my hand-referencing may have been incomplete, I just included `System.Memory`.

> There may also be a bug in here with regards tot he missing method exception.

Yep, pretty weird, since it compiles fine if you create a function with this code, but then when you run it, BOOM. ;).

> we should have a good experience in place for Span + FSI with .NET 5.

Sounds great! No rush. While I have no workaround for FSI, I can just compile & run to test. I won't be using spans daily anyway ;).

**Comment by dsyme** [comment]
The problem is that FSI ilreflect.fs is not emitting `modreq` attributes

```
    // Consider completing the following cases:                                                      
    | ILType.Modified (_, _, modifiedTy) -> 
        // Note, "modreq" are not being emitted. This is 
        convTypeAux cenv emEnv preferCreated modifiedTy
```

**Comment by dsyme** [comment]
> Unfortunately this is a symptom of the larger problem of span and byrefs with F# scripts. 

I don't think this is the problem in this case - there is something about that using Reflection to emit a call to the `get_Item` method that is unusual and not working correctly.

It is odd, as we do acquire the appropriate `MethodInfo` correctly and then call `ILGenerator.Emit`.  I don't see what is specifically wrong with that.  I had thought it was something to do with custom attributes but that doesn't apply here.

The call we need to emit is this:

```
  IL_000f:  call       instance !0& modreq([System.Runtime]System.Runtime.InteropServices.InAttribute) valuetype [System.Runtime]System.ReadOnlySpan`1<char>::get_Item(int32)
  IL_0014:  ldind.u2
```

I think we might need to make a standalone repro of emitting a call to that method and check if it works at all.

**Comment by dsyme** [comment]
The following C# code also gives the same exception.  I'm not sure what's going wrong

```
using System;
using System.Reflection;
using System.Reflection.Emit;


static class Program
{
    public static void Main()
    {
        var a = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("aa"), AssemblyBuilderAccess.Run);
        var m = a.DefineDynamicModule("MyDynamicAsm");
        var t = m.DefineType("MyDynamicType",TypeAttributes.Public);

        var mb = t.DefineMethod("foo", MethodAttributes.Public | MethodAttributes.Static, CallingConventions.Standard, typeof(char), new Type[] { typeof(string) });
        var ilg = mb.GetILGenerator();
        var minfo1 = typeof(MemoryExtensions).GetMethod("AsSpan", new Type[] { typeof(string) });
        var minfo2 = typeof(ReadOnlySpan<char>).GetMethod("get_Item", BindingFlags.Public | BindingFlags.Instance);
        ilg.Emit(OpCodes.Ldarg_0);
        ilg.Emit(OpCodes.Call, minfo1);
        ilg.Emit(OpCodes.Call, minfo2);
        ilg.Emit(OpCodes.Ret);
        t.CreateType();
        var m2 = t.GetMethod("foo");
        m2.Invoke(null, new object[] { "abc" });


    }
}
```

**Comment by dsyme** [comment]
Looks like you hit this one a while back @TIHan here: https://github.com/dotnet/runtime/issues/25958#issuecomment-481575399

That bug got closed yesterday as fixed for .NET vnext https://github.com/dotnet/runtime/issues/25958

In that case we can label this bug as external I think.  But span-manipulating code won't work well in F# interactive until the fix comes through the pipe

**Comment by abelbraaksma** [comment]
@dsyme That's a very interesting analysis, if I understand the referenced issue correctly, any emit with modreq or modopt and an `in` generic param would fail to emit proper IL. Which doesn't seem limited to spans. 

(side note, I never realized that fsi used `Reflection.Emit`,I'd have assumed it used the IL writer at have for fsc)

**Comment by abelbraaksma** [comment]
(this may well be the cause of many related reports on similar missing methods exn in FSI)

**Comment by dsyme** [comment]
> (this may well be the cause of many related reports on similar missing methods exn in FSI)

Any link to those bug reports?

**Comment by dsyme** [comment]
I'm really surprised this hasn't hit C# code that generates IL more.

**Comment by dsyme** [comment]
The bug has been confirmed fixed in .NET Core.  The fix will take a while to come through the pipe but I'm inclined to close this to avoid the book keeping.

**Comment by abelbraaksma** [comment]
> Any link to those bug reports?

@dsyme There were issues with dotnet fsi not loading all libraries for NetStandard, but I believe that's resolved meanwhile, so that point is moot now. 

I'll tentatively close this per your suggestion,apparently this was external?

**Comment by isaacabraham** [comment]
@abelbraaksma @cartermp was this indeed fixed? I've just seen this occur in FSI in latest Ionide (within a function that's been defined inside FSI).

**Comment by abelbraaksma** [comment]
@isaacabraham, indeed, it looks like the bug is back. The code from my original post fails with the same error (though I'm aware that you cannot return a Span on the heap, this doesn't appear to be the issue here since I'm returning a char).

Current situation:

```
SDK Version: 5.0.104

> #r "System.Memory.dll";;
--> Referenced 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.4\System.Memory.dll' (file may be locked by F# Interactive process)

> open System;;
> "1234".AsSpan().[1];;
System.MissingMethodException: Method not found: '!0 ByRef System.ReadOnlySpan`1.get_Item(Int32)'.
   at <StartupCode$FSI_0005>.$FSI_0005.main@()
Stopped due to error
```

It should be noted that if you're not trying to access `Item` or indirectly the same through `[x]`, spans seem to work fine:

```
> "1234".AsSpan().EndsWith("4".AsSpan());;
val it : bool = true
```

@isaacabraham, was it a different scenario you had, or similarly related to the use of the indexer function?

**Comment by cartermp** [comment]
This looks like it's resolved, but I mistakenly assigned it to a VS milestone. The fix in the runtime should be in .NET 6.

**Comment by isaacabraham** [comment]
@abelbraaksma can't remember now. I worked around it somehow but it was just a muck around with some Span, throwaway code.
